server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    mode: HTML
    enabled: true
  jackson:
    date-format: MM-dd HH:mm:ss
    time-zone: GMT+8